# Site
repository: austinjones/austinjones.github.io
favicon: images/favicon.ico

# Personal info
name: Austin Jones
title: // Backend Engineer
email: austinbaysjones@gmail.com
website: github.com/austinjones

# Social links
# twitter_username: 
github_username:  austinjones
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
linkedin_username: austinbaysjones
# pinterest_username: 
# youtube_username: 
# googleplus_username: +

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: > # this will include new lines to allow paragraphs
  Hi, I'm Austin.  I'm a professional Backend Engineer, with extensive <mark>Java</mark> and <mark>Rust</mark> experience.


  At work I design, build, and deploy <mark>Spring Boot</mark> services.  I've also done Systems work, mostly on <mark>AWS</mark>, 
  deploying Dockerized applications on EC2, and ALB/ECS.


  In my spare time I'm a Generative Artist (see [my portfolio](https://austinjones.onfabrik.com/portfolio/texture-from-nothing)).  
  I use Rust and GPUs to generate intricate images for canvas prints.  I use <mark>Machine Learning</mark> to solve creative problems 
  in <mark>Pytorch</mark>.

darkmode: false
# Projects Section
projects_title: Current Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  When I'm not working, my interests are:
   - Adventures on my <mark>Onewheel</mark>
   - PC gaming
   - Jazz Piano
   - Cooking

# Footer
footer_show_references: true

# Build settings
remote_theme: austinjones/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
